spring:
  application:
    name: student-service
  cloud:
    circuitbreaker:
      hystrix:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000
  timeout: 1000
ribbon:
 ConnectTimeout: 300000
 ReadTimeout: 300000
