eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: localhost
server:
  port: 0

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9292/oauth/check_token
      id: stock
    client:
      access-token-uri: http://localhost:9292/oauth/token
      user-authorization-uri: http://localhost:9292/oauth/authorize
      client-id: ourmind
      client-secret: cloud
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
